// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.2";

// src/lib/mcp/tools/list-leads.ts
import { defineTool, ToolError } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.95.3";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv(["SUPABASE_PUBLISHABLE_KEY", "VITE_SUPABASE_PUBLISHABLE_KEY"]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-leads.ts
var list_leads_default = defineTool({
  name: "list_leads",
  title: "List partner leads",
  description: "List partner application leads from the Subday partner portal, newest first. Optionally filter by status or city.",
  inputSchema: {
    status: z.string().trim().optional().describe("Filter by lead status (e.g. new, in_progress, done)."),
    city: z.string().trim().optional().describe("Filter by city (case-insensitive partial match)."),
    limit: z.number().int().min(1).max(100).optional().describe("Max number of leads to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, city, limit }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError("Not authenticated");
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("partner_leads").select("id,name,city,phone,venue,comment,status,note,created_at").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    if (city) query = query.ilike("city", `%${city}%`);
    const { data, error } = await query;
    if (error) throw new ToolError(error.message);
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? [], null, 2) }],
      structuredContent: { leads: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-lead.ts
import { defineTool as defineTool2, ToolError as ToolError2 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z2 } from "npm:zod@^3.25.76";
var get_lead_default = defineTool2({
  name: "get_lead",
  title: "Get a partner lead",
  description: "Fetch a single partner lead by its id.",
  inputSchema: { id: z2.string().uuid().describe("Lead id (UUID).") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError2("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("partner_leads").select("id,name,city,phone,venue,comment,status,note,created_at").eq("id", id).maybeSingle();
    if (error) throw new ToolError2(error.message);
    if (!data) throw new ToolError2(`No lead found with id ${id}`);
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/update-lead.ts
import { defineTool as defineTool3, ToolError as ToolError3 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z3 } from "npm:zod@^3.25.76";
var update_lead_default = defineTool3({
  name: "update_lead",
  title: "Update a partner lead",
  description: "Update the status and/or internal note of a partner lead.",
  inputSchema: {
    id: z3.string().uuid().describe("Lead id (UUID)."),
    status: z3.string().trim().min(1).optional().describe("New status, e.g. new, in_progress, done, rejected."),
    note: z3.string().trim().max(2e3).optional().describe("Internal note about this lead.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ id, status, note }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError3("Not authenticated");
    if (status === void 0 && note === void 0) throw new ToolError3("Provide status and/or note to update.");
    const supabase = supabaseForUser(ctx);
    const patch = {};
    if (status !== void 0) patch.status = status;
    if (note !== void 0) patch.note = note;
    const { data, error } = await supabase.from("partner_leads").update(patch).eq("id", id).select("id,name,status,note").maybeSingle();
    if (error) throw new ToolError3(error.message);
    if (!data) throw new ToolError3("Lead not found or you do not have permission to update it.");
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { lead: data }
    };
  }
});

// src/lib/mcp/tools/lead-stats.ts
import { defineTool as defineTool4, ToolError as ToolError4 } from "npm:@lovable.dev/mcp-js@0.26.2";
import { z as z4 } from "npm:zod@^3.25.76";
var lead_stats_default = defineTool4({
  name: "lead_stats",
  title: "Partner lead statistics",
  description: "Summarize partner leads: totals, counts by status, top cities, and leads in the last N days.",
  inputSchema: {
    days: z4.number().int().min(1).max(365).optional().describe("Window in days for the recent-lead count (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ days }, ctx) => {
    if (!ctx.isAuthenticated()) throw new ToolError4("Not authenticated");
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("partner_leads").select("status,city,created_at");
    if (error) throw new ToolError4(error.message);
    const rows = data ?? [];
    const window = days ?? 30;
    const since = Date.now() - window * 24 * 60 * 60 * 1e3;
    const byStatus = {};
    const byCity = {};
    let recent = 0;
    for (const row of rows) {
      const status = row.status ?? "new";
      byStatus[status] = (byStatus[status] ?? 0) + 1;
      const city = (row.city ?? "").trim() || "\u2014";
      byCity[city] = (byCity[city] ?? 0) + 1;
      if (row.created_at && new Date(row.created_at).getTime() >= since) recent += 1;
    }
    const topCities = Object.entries(byCity).sort((a, b) => b[1] - a[1]).slice(0, 10).map(([city, count]) => ({ city, count }));
    const summary = { total: rows.length, byStatus, topCities, windowDays: window, recent };
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: summary
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "rmmcnriwgpioojgleody";
var mcp_default = defineMcp({
  name: "subday-partner-portal",
  title: "Subday Partner Portal",
  version: "0.1.0",
  instructions: "Tools for the Subday partner portal. Use `list_leads` and `get_lead` to read partner applications, `update_lead` to set a lead's status or internal note, and `lead_stats` for aggregate numbers. All tools act as the signed-in Subday user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_leads_default, get_lead_default, update_lead_default, lead_stats_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.2/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
